y <- seq(-7, 7, length=125)
x <- y
fun <- function(x, y) sin(x^2+y^2)
z <- outer(x, y, fun)
z <- normalize(z)
#writeImage(z, "../doc/figures/rings.eps")
zs <- resize(z, nrow(z)/2, filter="Point")
#writeImage(zs, "../doc/figures/ringss.eps")
display(z)
display(zs)
zb <- EBI2biOps(z)
zbfft <- imgFFT(zb)
zbfftlp <- imgFFTLowPass(zbfft, 40)
zblp <- imgFFTInv(zbfftlp)
zlp <- biOps2EBI(zblp)
display(zlp)
zlps <- resize(zlp, nrow(z)/2, filter="Point")
display(zlps)