## Demo for p.9 Fig.2.2
y <- seq(-7, 7, length=125)
x <- y
fun <- function(x, y) sin(x^2+y^2)
z <- outer(x, y, fun)
z <- normalize(z)
display(z, title="Zone plate")
zs <- resize(z, nrow(z)/2, filter="Point")
display(zs, title="Zone plate resized")
zb <- E2b(z)
zbfft <- imgFFT(zb)
zbfftlp <- imgFFTLowPass(zbfft, 25)
zblp <- imgFFTInv(zbfftlp)
zlp <- b2E(zblp)
display(zlp, title="Zone plate low-pass filtered")
zlps <- resize(zlp, nrow(z)/2, filter="Point")
display(zlps, title="Zone plate resized after low-pass filtering")