## Demo for p.86 Fig.5.10
cup <- readImage(system.file("images/cupgirl.png", package="RImageBook"))
cupb <- E2b(cup)
cupbgn <- imgGaussianNoise(cupb, 0, 120)
cupbsp <- imgSaltPepperNoise(cupb, 5)
cupsp <- b2E(cupbsp)
cupgn <- b2E(cupbgn)
cupan50 <- AnisotropicFilter(cup, 50)
cupgnan <- AnisotropicFilter(cupgn, 10)
cupspan <- AnisotropicFilter(cupsp, 50)
display(cup, "Original image")
display(cupan50, "Anisotropic filter 50 times on the original image")
display(cupsp, "Salt and pepper noise")
display(cupspan, "Anisotropic filter 10 times on the salt and pepper noise")
display(cupgn, "Gaussian noise")
display(cupgnan, "Anisotropic filter 50 times on the gaussian noise")
