cup <- readImage(system.file("images/cupgirl.png", package="RImageBook"))
cupb <- EBI2biOps(cup)
cupbgn <- imgGaussianNoise(cupb, 0, 120)
cupbsp <- imgSaltPepperNoise(cupb, 5)
cupsp <- biOps2EBI(cupbsp)
cupgn <- biOps2EBI(cupbgn)
cupan50 <- AnisotropicFilter(cup, 50)
cupgnan <- AnisotropicFilter(cupgn, 10)
cupspan <- AnisotropicFilter(cupsp, 50)
display(cupan50)
display(cupspan)
display(cupgnan)