rlogo <- readImage("http://www.r-project.org/Rlogo.jpg") 
display(rlogo)
writeImage(rlogo, "Rlogo.jpg")

library(RCurl)
library(Rcompression)
sipi <- getBinaryURL("http://sipi.usc.edu/database/misc.zip")
con <- file("misc.zip","wb")
writeBin(sipi, con)
close(con)
unzip("misc.zip")
fz <- zipArchive("misc.zip")
names(fz)
img5 <- readImage(names(fz)[[5]])
display(img5)

library(RgoogleMaps)
mapurl <- GetMap(c(37,138), 5, maptype="satellite", RETURNIMAGE=FALSE)
map <- readImage(mapurl)
mapgr <- channel(map, "gray")
display(mapgr)