w <- matrix(c(0, 0, 0, 0.8), 128, 128)
h <- matrix(c(0, 0, 0, 0, 0, 0, 0, 0.8), 128, 128)
h <- t(h)
display(w)
display(h)
wbfft <- imgFFT(E2b(w))
hbfft <- imgFFT(E2b(h))
wbspec <- imgFFTSpectrum(wbfft)
hbspec <- imgFFTSpectrum(hbfft)
display(b2E(wbspec))
display(b2E(hbspec))


houses <- readImage(system.file("images/houses.png", package="RImageBook"))
housesb <- E2b(houses)
housesbfft <- imgFFT(housesb)
str(housesbfft)
housesbffti <- imgFFTInv(housesbfft)
display(b2E(housesbffti))

housesbspec <- imgFFTSpectrum(housesbfft)
display(b2E(housesbspec))

meanFilter <- matrix(1/25, 5, 5)
housesm <- filter2(houses, meanFilter)
gaussFilter <- GaussianKernel(11, 11, 1.8)
housesg <- filter2(houses, gaussFilter)
housesmbf <- imgFFT(E2b(housesm))
housesgbf <- imgFFT(E2b(housesg))
housesmbfspec <- imgFFTSpectrum(housesmbf)
housesgbfspec <- imgFFTSpectrum(housesgbf)
display(b2E(housesmbfspec))
display(b2E(housesgbfspec))

houseslpf <- imgFFTLowPass(housesbfft, 50)
houseslps <- imgFFTSpectrum(houseslpf)
houseslp <- imgFFTInv(houseslpf)
display(b2E(houseslps))
display(b2E(houseslp))

houseshpf <- imgFFTHighPass(housesbfft, 20)
houseshps <- imgFFTSpectrum(houseshpf)
houseshp <- imgFFTInv(houseshpf) 
display(b2E(houseshp))

housesbpf <- imgFFTBandPass(housesbfft, 20, 100)
housesbps <- imgFFTSpectrum(housesbpf)
housesbp <- imgFFTInv(housesbpf) 
display(b2E(housesbp))

w <- nrow(housesb)
h <- ncol(housesb)
gk <- GaussianKernel(w, h, 50)
housesglf <- housesbfft * (gk/max(gk))
housesghf <- housesbfft * (1 - gk/max(gk))
housesgls <- imgFFTSpectrum(housesglf)
housesghs <- imgFFTSpectrum(housesghf)
housesgl <- imgFFTInv(housesglf)
housesgh <- imgFFTInv(housesghf)
display(b2E(housesgl)); display(b2E(housesgh))
display(normalize(t(gk)))
display(normalize(t(1-gk)))