## Demo codes for p.13 Fig.2.5
f <- system.file("images/lena.tif", package="RImageBook")
lenab <- readTiff(f)
plot(lenab)
dev.new()
plot(imgCrop(lenab, 70, 150, 300, 300))
dev.new()
plot(imgEKMeans(lenab,4))
dev.new()
plot(imgDifferenceEdgeDetection(imgRGB2Grey(lenab)))
