## Demo for p.92 Fig.6.4
hft <- readImage(system.file("images/halftone.png", package="RImageBook"))
display(hft)
hftb <- E2b(hft)
hftfft <- imgFFT(hftb)
hftspec <- imgFFTSpectrum(hftfft)
hfts <- b2E(hftspec)
display(hfts)
hftsth <- thresh(hfts, 50, 50, 0.01)
kern <- makeBrush(3, "disc")
mask <- closing(opening(hftsth, kern))
mask <- drawCircle(mask, nrow(mask)/2, ncol(mask)/2, 40, col=0, fill=T)
display(mask)
maskb <- E2b(1-mask)
hftres <- hftfft * maskb
hftresspec <- imgFFTSpectrum(hftres)
hftresspece <- b2E(hftresspec)
display(hftresspece)
nonhalftone <- imgFFTInv(hftres)
display(normalize(b2E(nonhalftone)))