## Demo for p.126 Fig.7.27
## Requires RNiftyReg, bitops, oro.nifti packages
require(RNiftyReg)
require(bitops)
require(oro.nifti)
chest <- readImage(system.file("images/chest.png", package="RImageBook"))
chesttr <- translate(chest, c(20,30))
chestrt <- EBImage::rotate(chest, 20)
chestzo <- resize(chest, nrow(chest)*1.1)
display(chest)
display(chesttr)
display(chestrt)
display(chestzo)
chestn <- as.nifti(imageData(chest))
chesttrn <- as.nifti(imageData(chesttr))
chestrtn <- as.nifti(imageData(chestrt))
chestzon <- as.nifti(imageData(chestzo))
trnreg <- niftyreg(chesttrn, chestn)
rtreg <- niftyreg(chestrtn, chestn, nLevels=5)
zoreg <- niftyreg(chestzon, chestn)
display(trnreg$image)
display(rtreg$image)
display(zoreg$image)
decomposeAffine(trnreg$affine[[1]], chesttrn, chestn)
decomposeAffine(rtreg$affine[[1]], chestrtn, chestn)
decomposeAffine(zoreg$affine[[1]], chestzon, chestn)
