f <- system.file("images/lena.tif", package="RImageBook")
lena <- readImage(f)
writeImage(lena, "lena.png")
writeImage(lena, "lena1.jpg", quality=1)
writeImage(lena, "lena10.jpg", quality=10)
writeImage(lena, "lena50.jpg", quality=50)
writeImage(lena, "lena100.jpg", quality=100)
writeImage(lena, "lena.tiff")
display(readImage("lena.png"))
display(readImage("lena1.jpg"))
display(readImage("lena10.jpg"))
display(readImage("lena50.jpg"))
display(readImage("lena100.jpg"))
display(readImage("lena.tiff"))
