shapes <- readImage(system.file("images/shapes.png", package="EBImage"))
logo <- shapes[110:512,1:130]
display(logo)
logob <- E2b(logo)
logobn <- imgSaltPepperNoise(logob, 5)
logon <- b2E(logobn)
kern <- makeBrush(3, shape='diamond')
display(erode(logon, kern))
display(dilate(logon, kern))
display(opening(logon, kern))
display(closing(logon, kern))
display(closing(opening(logon, kern), kern))
display(opening(closing(logon, kern), kern))
