## Demo for p.104 Fig.7.4
shapes <- readImage(system.file("images/shapes.png", package="EBImage"))
logo <- shapes[110:512,1:130]
display(logo, "Original image")
logob <- E2b(logo)
logobn <- imgSaltPepperNoise(logob, 5)
logon <- b2E(logobn)
kern <- makeBrush(3, shape='diamond')
display(logon, "Noisy image")
display(erode(logon, kern), "Erosion")
display(dilate(logon, kern), "Dilation")
display(opening(logon, kern), "Opening")
display(closing(logon, kern), "Closing")
display(closing(opening(logon, kern), kern), "Opening and closing")
display(opening(closing(logon, kern), kern), "Closing and opening")
