logod <- distmap(logo, metric=c('euclidean'))
display(normalize(logod))
logol <- bwlabel(logo)
max(logol)

display(normalize(logol))
logolr <- rmObjects(logol, 3)
display(logolr)
logol2 <- reenumerate(logolr)
display(normalize(logol2))
max(logol2)

logolr <- rmObjects(logol, 3)
logolr <- logolr > 0
logol2 <- bwlabel(logolr)
max(logol2)

x <- matrix(0, 400, 400)
y <- drawCircle(x, 100, 200, 60, col=1, fill=TRUE)
z <- drawCircle(y, 200, 200, 60, col=1, fill=TRUE)
display(z)
w <- distmap(z)
wt <- watershed(w)
display(normalize(w))
display(normalize(wt))
gel <- readImage(system.file("images/ima7.gif", package="RImageBook"))
display(1-gel)
gelbw <- thresh(1-gel, w=8, h=8, offset=0.01)
display(gelbw)
kern <- makeBrush(3, shape="diamond")
gelbwsm <- closing(opening(gelbw, kern), kern)
display(gelbwsm)
geldist <- distmap(gelbwsm)
display(normalize(geldist))
gelwsh02 <- watershed(geldist, tolerance=0.2)
gelwsh10 <- watershed(geldist, tolerance=1)
gelwsh40 <- watershed(geldist, tolerance=4)
gelresult <- combine(normalize(gelwsh02),
                     normalize(gelwsh10),
                     normalize(gelwsh40))
display(gelresult)
x <- matrix(0, 400, 400)
y <- drawCircle(x, 100, 200, 60, col=1, fill=TRUE)
z <- drawCircle(y, 250, 200, 120, col=1, fill=TRUE)
display(z, title="original")
dm <- distmap(z)
display(normalize(dm))
wsh <- watershed(dm)
display(normalize(wsh), title="watershed")
peaks <- findPeaks(dm)
display(normalize(peaks), title="peaks")
seg1 <- propagate(z, bwlabel(peaks), z)
display(normalize(seg1), title="segmentaion by peak seeds")
peakval <- dm * peaks
min2 <- sort(unique(as.vector(peakval)))[2] 
seeds <- dm >= min2
seeds <- bwlabel(seeds)
display(normalize(seeds), title="seeds")
seg2 <- propagate(z, seeds, z)
display(normalize(seg2), title="new segmentation")
