## Demo for p.76 Fig.5.3
cup <- readImage(system.file("images/cupgirl.png", package="RImageBook"))
cupb <- E2b(cup)
cupbgn <- imgGaussianNoise(cupb, 0, 120)
cupbsp <- imgSaltPepperNoise(cupb, 5)
cupgn <- b2E(cupbgn)
cupsp <- b2E(cupbsp)
display(cup)
display(cupgn)
display(cupsp)

cupgauss <- gblur(cup, 3, 1)
display(cupgauss)

gauss9 <- GaussianKernel(9, 9, 5)
cupgauss9 <- filter2(cup, gauss9)
display(cupgauss9)

meanFilter <- matrix(1/9, 3, 3)
cupmean <- filter2(cup, meanFilter)
cupspmean <- filter2(cupsp, meanFilter)
cupgnmean <- filter2(cupgn, meanFilter)
display(cupmean)
display(cupspmean)
display(cupgnmean)

gsfilter <- GaussianKernel(3, 3, 2)
cupgauss <- filter2(cup, gsfilter)
cupgngauss <- filter2(cupgn, gsfilter)
cupspgauss <- filter2(cupsp, gsfilter)
display(cupgauss)
display(cupgngauss)
display(cupspgauss)

cupbmed <- imgBlockMedianFilter(cupb)
cupbgnmed <- imgBlockMedianFilter(cupbgn)
cupbspmed <- imgBlockMedianFilter(cupbsp)
display(b2E(cupbmed))
display(b2E(cupbgnmed))
display(b2E(cupbspmed))