hft <- readImage("../src/RImgBook/inst/images/halftone.png")
display(hft)
hftb <- EBI2biOps(hft)
hftfft <- imgFFT(hftb)
hftspec <- imgFFTSpectrum(hftfft)
plot(hftspec)
hfts <- biOps2EBI(hftspec)
writeImage(hftonespece, "../doc/figures/hftonespec.eps")
display(hfts)
writeImage(hfts, "../doc/figures/hfts.eps")
display(thresh(hfts, 50, 50, 0.01))
hftsth <- thresh(hfts, 50, 50, 0.01)
kern <- makeBrush(3, "disc")
mask <- closing(opening(hftsth, kern))
mask <- drawCircle(mask, nrow(mask)/2, ncol(mask)/2, 40, col=0, fill=T)
display(mask)
writeImage(mask, "../doc/figures/hftrmask.eps")
maskb <- EBI2biOps(1-mask)
hftres <- hftfft * maskb
hftresspec <- imgFFTSpectrum(hftres)
plot(hftresspec)
hftresspece <- biOps2EBI(hftresspec)
writeImage(hftresspece, "../doc/figures/hftresspece.eps")
nonhalftone <- imgFFTInv(hftres)
display(normalize(biOps2EBI(nonhalftone)))
writeImage(normalize(biOps2EBI(nonhalftone)), "../doc/figures/nonhalftone.eps")


