y <- seq(-7, 7, length=125)
x <- y
fun <- function(x, y) sin(x^2+y^2)
z <- outer(x, y, fun)
z <- normalize(z)
zs <- resize(z, nrow(z)/2, filter="Point")
display(z)
display(zs)
zb <- E2b(z)
zbfft <- imgFFT(zb)
zbfftlp <- imgFFTLowPass(zbfft, 25)
zblp <- imgFFTInv(zbfftlp)
zlp <- b2E(zblp)
display(zlp)
zlps <- resize(zlp, nrow(z)/2, filter="Point")
display(zlps)