x <- 0:65535
mat <- matrix(0.3*sin(x*pi/50)+0.7, 256, 256)
display(mat)
img <- readImage(system.file("images/lena.bmp", package="RImageBook"))
display(normalize(img * mat))
d <- img * mat
db <- E2b(d)
df <- imgFFT(db)
dfs <- imgFFTSpectrum(df)
plot(dfs)
dfse <- b2E(dfs)
display(dfse)
display(thresh(dfse, 40, 40, 0.05))
dfseth <- thresh(dfse, 40, 40, 0.05)
kern <- makeBrush(7, "disc")
mask <- opening(dfseth, kern)
mask <- closing(opening(dfseth, kern), kern)
mask <- drawCircle(mask, nrow(mask)/2, ncol(mask)/2, 30, col=0, fill=T)
display(mask)
c <- E2b(1-mask)
dfc <- df * c
spec <- imgFFTSpectrum(dfc)
plot(spec)
display(b2E(spec))
nonhalftone <- imgFFTInv(dfc)
display(normalize(b2E(nonhalftone)))